name: recette_plus
description: "Une marketplace culinaire moderne"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Extra 
  shared_preferences: ^2.2.2
  provider: ^6.1.1
  image_picker: ^1.0.4
  url_launcher: ^6.2.2
  video_player: ^2.8.1
  chewie: ^1.7.1
  permission_handler: ^11.3.1
  flutter_local_notifications: ^17.2.2
  firebase_core: ^3.6.0
  firebase_messaging: ^15.1.3
  http: ^1.2.1
  workmanager: ^0.6.0
  
  # Utils
  intl: ^0.19.0
  uuid: ^4.4.0
  
  # SVG & Images
  flutter_svg: ^2.0.10+1
  cached_network_image: ^3.3.1

  # UI & Design
  cupertino_icons: ^1.0.2
  google_fonts: ^6.1.0


  # State Management & Architecture
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5

  # Backend & Database
  supabase_flutter: ^2.9.1

  google_sign_in: ^6.1.6

  # Environment & Configuration
  flutter_dotenv: ^5.1.0

  # icone de l'appli
  flutter_launcher_icons: ^0.14.4


flutter_launcher_icons : 
  android : true
  ios : true
  image_path : "assets/images/logo_mini.png"

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/logo.png
    - assets/images/logo_mini.png
    - assets/images/food-illustration.svg
    - .env

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo_mini.png"
  min_sdk_android: 21
  web:
    generate: true
    image_path: "assets/images/logo_mini.png"
    background_color: "#hexcode"
    theme_color: "#hexcode"
  windows:
    generate: true
    image_path: "assets/images/logo_mini.png"
    icon_size: 48
  macos:
    generate: true
    image_path: "assets/images/logo_mini.png"